resources:
  grist:
    storage: 5Gi
    replicas: 1
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 256Mi

  n8n:
    replicas: 1
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 50m
      memory: 256Mi

  redis:
    storage: 2Gi
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 50Mi

  database:
    storage: 10Gi
    replicas: 2
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
