---
- name: Deploy PostgreSQL
  hosts: all
  roles:
    - postgres
  tags: [postgres]

- name: Deploy Redis
  hosts: all
  roles:
    - redis
  tags: [redis]

- name: Deploy Grist
  hosts: all
  roles:
    - grist
  tags: [grist]
