---
- name: Deploy secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
    apply:
      tags: [grist.secrets]
  tags: [grist.secrets]

- name: Deploy storage
  ansible.builtin.include_tasks:
    file: storage.yml
    apply:
      tags: [grist.storage]
  tags: [grist.storage]

- name: Deploy web application
  ansible.builtin.include_tasks:
    file: web.yml
    apply:
      tags: [grist.web]
  tags: [grist.web]
