---
- name: Deploy secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
    apply:
      tags: [outline.secrets]
  tags: [outline.secrets]

- name: Deploy storage
  ansible.builtin.include_tasks:
    file: storage.yml
    apply:
      tags: [outline.storage]
  tags: [outline.storage]

- name: Deploy web application
  ansible.builtin.include_tasks:
    file: web.yml
    apply:
      tags: [outline.web]
  tags: [outline.web]
