---
- name: Create database credentials secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "grist-db-credentials"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: database
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ database.grist.user }}"
        password: "{{ secrets.database.grist.password }}"
        database: "{{ database.grist.name }}"

- name: Create application secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "grist-secrets"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: grist
      type: Opaque
      stringData:
        APP_HOME_URL: "{{ app.url }}"
        APP_DOC_URL: "{{ app.url }}"
        TYPEORM_DATABASE: "{{ database.grist.name }}"
        TYPEORM_HOST: "{{ database.host }}"
        TYPEORM_LOGGING: "false"
        TYPEORM_PORT: "5432"
        TYPEORM_TYPE: "postgres"
        TYPEORM_USERNAME: "{{ database.grist.user }}"
        TYPEORM_PASSWORD: "{{ secrets.database.grist.password }}"
        REDIS_URL: "redis://{{ app.name }}-redis:6379"
        GRIST_OIDC_IDP_ISSUER: "{{ secrets.oidc.issuer }}"
        GRIST_OIDC_IDP_CLIENT_ID: "{{ secrets.oidc.client_id }}"
        GRIST_OIDC_IDP_CLIENT_SECRET: "{{ secrets.oidc.client_secret }}"
        GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED: "true"
        GRIST_FORCE_LOGIN: "true"
        ALLOWED_WEBHOOK_DOMAINS: "*"
        GRIST_ALLOWED_ORIGINS: "*"
