---
- name: Create storage
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app.name }}-grist-storage"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: storage
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: "{{ resources.grist.storage }}"
        storageClassName: "{{ storage_class.name }}"
