---
- name: Restore backup in a new cluster
  kubernetes.core.k8s:
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: "{{ database.cluster }}"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: database
        annotations:
          cnpg.io/skipEmptyWalArchiveCheck: "enabled"
      spec:
        instances: "{{ resources.database.replicas }}"
        storage:
          size: "{{ resources.database.storage }}"
          storageClass: "{{ storage_class.name }}"
        enableSuperuserAccess: true
        resources:
          requests:
            cpu: "{{ resources.database.requests.cpu }}"
            memory: "{{ resources.database.requests.memory }}"
          limits:
            memory: "{{ resources.database.limits.memory }}"
        backup:
          barmanObjectStore:
            destinationPath: "s3://{{ secrets.s3.name }}"
            endpointURL: "https://{{ secrets.s3.host }}"
            serverName: "{{ database.cluster }}"
            s3Credentials:
              accessKeyId:
                name: s3-credentials
                key: AWS_ACCESS_KEY_ID
              secretAccessKey:
                name: s3-credentials
                key: AWS_SECRET_ACCESS_KEY
              wal:
                maxParallel: 8
        bootstrap:
          recovery:
            source: s3-restore
            recoveryTarget:
              target: latest
        externalClusters:
          - name: s3-restore
            barmanObjectStore:
              destinationPath: "s3://{{ secrets.s3.name }}"
              endpointURL: "https://{{ secrets.s3.host }}"
              serverName: "{{ database.cluster }}"
              s3Credentials:
                accessKeyId:
                  name: s3-credentials
                  key: AWS_ACCESS_KEY_ID
                secretAccessKey:
                  name: s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
              wal:
                maxParallel: 8
        env:
          - name: AWS_REQUEST_CHECKSUM_CALCULATION
            value: WHEN_REQUIRED
          - name: AWS_RESPONSE_CHECKSUM_VALIDATION
            value: WHEN_REQUIRED
        managed:
          roles:
            - name: "{{ database.grist.user }}"
              ensure: present
              login: true
              superuser: false
              passwordSecret:
                name: "{{ app.name }}-grist-db-credentials"
            - name: "{{ database.n8n.user }}"
              ensure: present
              login: true
              superuser: false
              passwordSecret:
                name: "{{ n8n.name }}-db-credentials"
  tags:
    - never
    - postgres.restore
